document.writeln("<style>");
document.writeln(".banl { max-height:400px; overflow:hidden;}");
document.writeln(".banl .zjtab{ position:relative; left:50%; margin-top:-5%; float:left;}");
document.writeln(".banl .zjtab ul{ position:relative; left:-50%; top:0%;}");
document.writeln(".banl .zjtab ul li{ float:left; margin:0% 5px;}");
document.writeln(".banl .zjtab li .zjtab_1{ display:none;}");
document.writeln(".banl .zjtab li .zjtab_2{ display:block;}");
document.writeln(".banl .zjtab li.over .zjtab_1{ display:block;}");
document.writeln(".banl .zjtab li.over .zjtab_2{ display:none;}");
document.writeln(".banl .zjcons ul li images{ display:block; width:100%;}");
document.writeln("</style>");
document.writeln("<div class='banl'>");
document.writeln("	<div class='zjbox' id='zjbox'>");
document.writeln("    	<div class='zjcons'>");
document.writeln("        	<ul>");
document.writeln("            	<li><a href='/zt/yhzt/'><images src='/public/images/banl_0.jpg' /></a></li>");
document.writeln("                <li><a href='/zt/tmj/'><images src='/public/images/tmj.jpg' /></a></li>");
document.writeln("                <li><a href='javascript:;' onclick='swtClick();'><images src='/public/images/480.jpg' /></a></li>");
document.writeln("                <li><a href='javascript:;' onclick='swtClick();'><images src='/public/images/banl_1.jpg' /></a></li>");
document.writeln("                <li><a href='javascript:;' onclick='swtClick();'><images src='/public/images/banl_3.jpg' /></a></li>");
document.writeln("                <li><a href='javascript:;' onclick='swtClick();'><images src='/public/images/banl_4.jpg' /></a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        <div class='zjtab'>");
document.writeln("        	<ul>");
document.writeln("                <li><images src='/public/images/qhal_1.png' class='zjtab_1' /><images src='/public/images/qhal_2.png' class='zjtab_2' /></li>");
document.writeln("                <li><images src='/public/images/qhal_1.png' class='zjtab_1' /><images src='/public/images/qhal_2.png' class='zjtab_2' /></li>");
document.writeln("                <li><images src='/public/images/qhal_1.png' class='zjtab_1' /><images src='/public/images/qhal_2.png' class='zjtab_2' /></li>");
document.writeln("                <li><images src='/public/images/qhal_1.png' class='zjtab_1' /><images src='/public/images/qhal_2.png' class='zjtab_2' /></li>");
document.writeln("                <li><images src='/public/images/qhal_1.png' class='zjtab_1' /><images src='/public/images/qhal_2.png' class='zjtab_2' /></li>");
document.writeln("                <li><images src='/public/images/qhal_1.png' class='zjtab_1' /><images src='/public/images/qhal_2.png' class='zjtab_2' /></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
